#This copies the .jar file located at roles/petclinic/files/ into the the specified destination.
#No need to specify the path on source as Ansible looks for the file into said directory as it is using a role
- name: copy the jar
  copy:
    src: spring-petclinic-3.3.0-SNAPSHOT.jar
    dest: /home/cloud_user/petclinic.jar
