#When working with roles, Ansible will look at first into main.yml named files
#This main.yml file groups the other tasks and runs all of them.
#For this, the import_tasks attribute is needed
- name: install dependencies
  import_tasks: install-dependencies.yml

- name: get jar
  import_tasks: get-jar.yml

- name: modify ufw
  import_tasks: modify-ufw.yml  

- name: deploy petclinic
  import_tasks: deploy-petclinic.yml
